In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("housing.csv")

In [3]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [5]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [7]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

In [8]:
df.value_counts()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  population  households  median_income  median_house_value  ocean_proximity
-114.31    34.19     15.0                5612.0       1283.0          1015.0      472.0       1.4936         66900.0             INLAND             1
-114.61    33.62     16.0                1187.0       261.0           1115.0      242.0       2.1759         61500.0             INLAND             1
-114.62    33.62     26.0                18.0         3.0             5.0         3.0         0.5360         275000.0            INLAND             1
-114.63    32.76     15.0                1448.0       378.0           949.0       300.0       0.8585         45000.0             INLAND             1
-114.64    34.83     10.0                2502.0       573.0           1152.0      481.0       1.7062         86800.0             INLAND             1
                                                                                                                                                   ..
-124.25    40.28     32.0                1430.0       419.0           434.0       187.0       1.9417         76100.0             NEAR OCEAN         1
-124.26    40.58     52.0                2217.0       394.0           907.0       369.0       2.3571         111400.0            NEAR OCEAN         1
-124.27    40.69     36.0                2349.0       528.0           1194.0      465.0       2.5179         79000.0             NEAR OCEAN         1
-124.30    41.84     17.0                2677.0       531.0           1244.0      456.0       3.0313         103600.0            NEAR OCEAN         1
           41.80     19.0                2672.0       552.0           1298.0      478.0       1.9797         85800.0             NEAR OCEAN         1
Name: count, Length: 20433, dtype: int64

In [9]:
df["ocean_proximity"].value_counts()

ocean_proximity
<1H OCEAN     9136
INLAND        6551
NEAR OCEAN    2658
NEAR BAY      2290
ISLAND           5
Name: count, dtype: int64

In [10]:
import numpy as np

In [2]:
def make_test_train(data, test_ratio):
    np.random.seed(20)
    shuffled_indices=np.random.permutation(len(data))
    test_set_size=int(len(data)*test_ratio)
    test_indices=shuffled_indices[:test_set_size]
    train_indices=shuffled_indices[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

    # this method is not good as splitting can be uneven it may be possible that one type of data goes whole in train set or test set.
    # So we will do Stratified sampling using scikit-learn

In [18]:
train, test=make_test_train(df,0.2)

In [19]:
train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
7728,-118.13,33.92,28.0,3069.0,864.0,1932.0,835.0,2.4925,177200.0,<1H OCEAN
14565,-117.20,32.84,32.0,2033.0,394.0,989.0,389.0,3.2583,181400.0,NEAR OCEAN
8099,-118.22,33.81,41.0,726.0,166.0,602.0,183.0,3.7885,156900.0,NEAR OCEAN
4772,-118.34,34.04,42.0,1681.0,360.0,987.0,337.0,2.6000,171400.0,<1H OCEAN
11663,-118.02,33.85,31.0,1922.0,329.0,1030.0,353.0,5.3416,213000.0,<1H OCEAN
...,...,...,...,...,...,...,...,...,...,...
1607,-122.08,37.87,24.0,6130.0,1359.0,1750.0,1286.0,2.9167,102700.0,NEAR BAY
3915,-118.52,34.19,37.0,1560.0,275.0,763.0,284.0,3.8516,206900.0,<1H OCEAN
14729,-117.02,32.80,31.0,2692.0,445.0,1129.0,450.0,4.4583,170000.0,<1H OCEAN
4367,-118.27,34.10,41.0,3729.0,740.0,1364.0,707.0,5.7778,412700.0,<1H OCEAN
15715,-122.45,37.79,46.0,2009.0,464.0,761.0,453.0,3.7188,500001.0,NEAR BAY

In [20]:
test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
6111,-117.90,34.13,25.0,3076.0,856.0,2868.0,752.0,2.6619,117600.0,<1H OCEAN
17742,-121.78,37.31,7.0,1973.0,328.0,1047.0,303.0,6.2340,292200.0,<1H OCEAN
79,-122.28,37.80,38.0,684.0,176.0,344.0,155.0,2.0114,131300.0,NEAR BAY
13150,-121.47,36.92,27.0,2049.0,417.0,1230.0,336.0,4.6477,265900.0,INLAND
527,-122.25,37.77,52.0,1038.0,220.0,482.0,215.0,3.1771,210200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
16880,-122.39,37.59,32.0,4497.0,NaN,1846.0,715.0,6.1323,500001.0,NEAR OCEAN
2018,-119.80,36.72,15.0,1908.0,417.0,1383.0,375.0,1.0472,57800.0,INLAND
3000,-119.03,35.30,10.0,829.0,146.0,447.0,173.0,4.1484,102900.0,INLAND
18393,-121.86,37.27,19.0,1852.0,268.0,866.0,272.0,5.6139,279500.0,<1H OCEAN
11945,-117.43,33.93,15.0,4836.0,1368.0,3012.0,1240.0,2.1865,129300.0,INLAND